apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace.name }}
data:
  NODE_ENV: {{ .Values.todoapp.config.nodeEnv | quote }}
  PORT: {{ .Values.todoapp.config.port | quote }}
  MONGODB_URI: "mongodb://{{ .Release.Name }}-mongo-service:{{ .Values.mongo.service.port }}/todolist"