apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
  - port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.targetPort }}