apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-deployment
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
      - name: mongo
        image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongo.service.targetPort }}
        resources:
          {{- toYaml .Values.mongo.resources | nindent 10 }}
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        {{- if eq .Values.mongo.storage.type "emptyDir" }}
        emptyDir: {}
        {{- end }}